TOKEN="" # Token here
CHAT_ID="" # Chat id here

LOG_FILE="tg-send.log"

# Estados y emojis (formato JSON) - SIN comentarios dentro del JSON
STATES='{
    "default": "ℹ️ INFO",
    "ok": "✅ OK",
    "warning": "⚠️ WARNING",
    "error": "❌ ERROR",
    "fail": "🔥 FAIL",
    "critical": "🚨 CRITICAL",
    "downloaded": "⬇️ DOWNLOADED",
    "custom": "🎯 CUSTOM"
}'
